# NumPy (Numerical Python)

* 수학 및 과학적 연산을 쉽고 빠르게 지원
* 다차원 <font color = 'blue'>행렬</font>(Array/Matrix)을 효과적으로 처리
* 일반적으로 <font color = 'red'>같은 데이터 타입 값</font>으로 구성
* https://numpy.org

In [ ]:
import warnings
warnings.filterwarnings('ignore')

# I. NumPy Package <font color='blue'>import ~ as

In [ ]:
import numpy as np

* Version Check

In [ ]:
np.__version__

'1.22.4'

# II. Array 생성

* Python <font color = 'blue'>List 구조</font>를 사용

>## 1) Scalar - <font color='red'>0D Array</font> - <font color='blue'>Rank0 Tensor

In [ ]:
a0 = np.array(9)

In [ ]:
print(a0)

9


>## 2) Vector - <font color='red'>1D Array</font> - <font color='blue'>Rank1 Tensor

In [ ]:
a1 = np.array([1, 3, 5, 7, 9])

In [ ]:
print(a1)

[1 3 5 7 9]


In [ ]:
a1[2]

5

In [ ]:
a1[1:3]

array([3, 5])

>## 3) Matrix - <font color='red'>2D Array</font> - <font color='blue'>Rank2 Tensor

In [ ]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

In [ ]:
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


* a2[행]

In [ ]:
a2[1]

array([4, 5, 6])

* a2[행, 열]

In [ ]:
a2[1, 1]

5

* a2[<font color = 'blue'>행</font>, 열]

In [ ]:
a2[:, 1]

array([2, 5, 8])

>## 4) Array - <font color='red'>3D Array</font> - <font color='blue'>Rank3 Tensor

In [ ]:
a3 = np.array([[[1, 2],
                [3, 4]],
               [[5, 6],
                [7, 8]],
               [[9, 10],
                [11, 12]]])

In [ ]:
print(a3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


* a3[축]

In [ ]:
a3[1]

array([[5, 6],
       [7, 8]])

* a3[축, 행]

In [ ]:
a3[1, 1]

array([7, 8])

* a3[축, 행, 열]

In [ ]:
a3[1, 1, 1]

8

* a3[<font color = 'blue'>축</font>, 행, 열]

In [ ]:
a3[:, 0, 0]

array([1, 5, 9])

* a3[<font color = 'blue'>축</font>, <font color = 'blue'>행</font>, 열]

In [ ]:
a3[:, :, 0]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

# III. AR<font color='red'>.shape</font> and AR<font color='blue'>.reshape( )

In [ ]:
AR = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [ ]:
print(AR)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


>## 1) <font color='red'>.shape

* 행렬 크기

In [ ]:
AR.shape

(12,)

* 행렬 차원

In [ ]:
AR.ndim

1

* 행렬 원소 개수

In [ ]:
AR.size

12

>## 2) <font color='blue'>.reshape(3, 4)

* <font color = 'blue'>.reshape(</font>행, 열<font color = 'blue'>)</font>

In [ ]:
AR2 = AR.reshape(3, 4)

In [ ]:
print(AR2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


* 행렬 크기

In [ ]:
AR2.shape

(3, 4)

* 행렬 차원

In [ ]:
AR2.ndim

2

* 행렬 원소 개수

In [ ]:
AR2.size

12

>## 3) <font color='blue'>.reshape(3, 2, 2)

* .reshape(<font color = 'red'>축</font>, 행, 열)

In [ ]:
AR3 = AR.reshape(3, 2, 2)

In [ ]:
print(AR3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


* 행렬의 크기

In [ ]:
AR3.shape

(3, 2, 2)

* 행렬의 차원

In [ ]:
AR3.ndim

3

* 행렬의 원소 개수

In [ ]:
AR3.size

12

>## 4) .reshape(<font color = 'red'>-1</font>, 1)

* .reshape(<font color = 'red'>12</font>, 1)

In [ ]:
AR.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

   * .reshape(1, <font color = 'blue'>12</font>)

In [ ]:
AR2.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
AR2.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
AR3.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

* <font color = 'blue'>.flatten( )

In [ ]:
AR3.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# IV. 범위 지정(arange) 함수

>## 1) 연속된 10개 값 생성

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

>## 2) 1부터 9까지 <font color = 'blue'>1간격</font>으로 생성

In [ ]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

>## 3) 1부터 9까지 <font color = 'red'>2간격</font>으로 생성

In [ ]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

>## 4) Array 생성 후 <font color = 'blue'>.reshape( )</font> 적용

In [ ]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# V. 특별한 형태의 Array 생성

>## 1) 0과 1로만 구성된 Array

* <font color = 'blue'>0으로만 구성

In [ ]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

* <font color = 'blue'>1로만 구성

In [ ]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones([4, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* 산술연산을 적용하여 <font color = 'blue'>'9'로만 구성</font>된 행렬 생성

In [ ]:
np.zeros([3, 4]) + 9

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

>## 2) 3 x 3 <font color = 'red'>단위행렬

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

>## 3) 난수 Array 생성

* <font color = 'blue'>실수</font> 난수 생성
 - (축, 행, 열)

In [ ]:
np.random.rand(3, 2, 2)

array([[[0.64848452, 0.99506736],
        [0.07311662, 0.12909484]],

       [[0.74977182, 0.85048786],
        [0.85663604, 0.37699742]],

       [[0.98785292, 0.54096569],
        [0.41338835, 0.50345139]]])

* 주어진 <font color = 'blue'>정수</font> 범위에서 난수 생성
 - 1 ~ 44 사이
 - 복원 추출
 - (행, 열)

In [ ]:
np.random.randint(1, 45, size = (5, 6))

array([[ 8, 27, 41, 43, 10, 27],
       [40, 25, 19, 18, 36, 42],
       [25, 38, 22, 15,  8,  7],
       [11, 14, 38, 28, 33,  2],
       [ 8, 37, 35, 33, 31, 17]])

* np.random.<font color = 'red'>seed( )</font>
 - 의사난수(Pseudo Random Number) 생성 초기값 지정
 - <font color = 'red'>항상 같은 난수 생성</font>
 - 비복원 추출

In [ ]:
np.random.seed(2045)

np.random.choice(np.arange(1, 46), size = (5 ,6), replace = False)

array([[ 7, 32,  6, 41,  4, 34],
       [30, 28, 16,  5, 38, 33],
       [31, 13, 25, 23, 43, 12],
       [45,  8, 29, 22, 18,  9],
       [21, 20, 40,  2, 37, 39]])

* <font color = 'blue'>shuffle( )</font>
 - 원소 섞기

In [ ]:
TA = np.arange(1, 10)

TA

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(TA)

TA

array([7, 6, 5, 4, 3, 1, 8, 2, 9])

# VI. Array 연산

In [ ]:
A1 = np.array([85, 93, 75, 97, 69])

A2 = np.array([91, 90, 85, 97, 89])

A3 = np.array([[85, 93, 75],
               [90, 84, 97],
               [99, 91, 80]])

>## 1) 기본 연산

* 각각의 <font color = 'blue'>행과 열의 값을 매칭</font>하여 연산 수행

In [ ]:
A1 + A2

array([176, 183, 160, 194, 158])

In [ ]:
A2 - A1

array([ 6, -3, 10,  0, 20])

In [ ]:
A1 * A2

array([7735, 8370, 6375, 9409, 6141])

In [ ]:
A2 / A1

array([1.07058824, 0.96774194, 1.13333333, 1.        , 1.28985507])

In [ ]:
A1 * 3

array([255, 279, 225, 291, 207])

In [ ]:
A1 ** 2

array([7225, 8649, 5625, 9409, 4761])

>## 2) 통계량 연산

* 총합

In [ ]:
A1.sum()

419

* 평균

In [ ]:
A2.mean()

90.4

* 분산
 - 'ddof = 0'

In [ ]:
A2.var()

15.040000000000001

* 표준 편차
 - 'ddof = 0'

In [ ]:
A2.std()

3.8781438859330635

* 최소값

In [ ]:
A2.min()

85

> * A3 전체 최소값

  

In [ ]:
A3.min()

75

> * A3 각 열의 최소값

In [ ]:
A3.min(axis = 0)

array([85, 84, 75])

> * A3 각 행의 최소값

In [ ]:
A3.min(axis = 1)

array([75, 84, 80])

In [ ]:
A3.min(axis = 1, keepdims = True)

array([[75],
       [84],
       [80]])

* 최대값

In [ ]:
A2.max()

97

> * A3 전체 최대값

In [ ]:
A3.max()

99

> * A3 각 열의 최대값

In [ ]:
A3.max(axis = 0)

array([99, 93, 97])

> * A3 각 행의 최대값

In [ ]:
A3.max(axis = 1)

array([93, 97, 99])

In [ ]:
A3.max(axis = 1, keepdims = True)

array([[93],
       [97],
       [99]])

* 누적(Cumulative)합

In [ ]:
A1.cumsum()

array([ 85, 178, 253, 350, 419])

* 누적(Cumulative)곱

In [ ]:
A1.cumprod()

array([        85,       7905,     592875,   57508875, 3968112375])

# VII. Matrix 연산

* M1, M2 지정

In [ ]:
M1 = np.array([2, 4, 6, 8]).reshape(2, 2)

In [ ]:
print(M1)

[[2 4]
 [6 8]]


In [ ]:
M2 = np.array([3, 5, 7, 9]).reshape(2, 2)

In [ ]:
print(M2)

[[3 5]
 [7 9]]


>## 1) Matrix 곱

* <font color='red'>M1 @ M2

In [ ]:
M1.dot(M2)

array([[ 34,  46],
       [ 74, 102]])

* <font color='blue'>M2 @ M1

In [ ]:
np.dot(M2, M1)

array([[ 36,  52],
       [ 68, 100]])

* <font color='red'>Warning</font>: M1 * M2

In [ ]:
M1 * M2

array([[ 6, 20],
       [42, 72]])

In [ ]:
M2 * M1

array([[ 6, 20],
       [42, 72]])

>## 2) 전치 행렬

* M1의 전치 행렬

In [ ]:
np.transpose(M1)

array([[2, 6],
       [4, 8]])

* M2의 전치 행렬

In [ ]:
M2.transpose()

array([[3, 7],
       [5, 9]])

In [ ]:
M2.T

array([[3, 7],
       [5, 9]])

#
#
#
# The End
#
#
#